# .readthedocs.yml
# Minimal Read the Docs configuration
version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Python configuration
python:
  version: "3.11"
  install:
    - method: pip
      path: .
      extra_requirements: ["docs"]
    - requirements: requirements-docs.txt

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Optional: Uncomment to build PDF as well
# formats: [pdf]
